sudo: required

language: java

jdk:
 - oraclejdk8

sudo: enabled

addons:
  postgresql: "9.5"

before_script:
  - psql -c "create database jpa;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'admin'"

services:
  - postgresql

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=true -B

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: clinical-center-psw-isa

dist: trusty