sudo: required

language: java

jdk:
 - oraclejdk8

sudo: enabled

addons:
  postgresql: "12"

before_script:
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
  - sudo apt update
  - sudo apt -y install postgresql-12 postgresql-client-12
  - psql -c "create database jpa;" -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'admin'"

services:
  - postgresql

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: clinical-center-psw-isa

dist: trusty