sudo: required
language: java
jdk:
 - oraclejdk8
services:
  - postgresql
before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install -DskipTests=false -B
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: clinical-center-psw-isa
dist: trusty